### ISSUE TITLE
 ERROR: Could not resolve "buffer"

### ISSUE THREAD

**Issue by trentrae** [workerforce/unifi-ddns#33]
Working through this configuration for the first time / fresh setup:
Ubuntu 20.04..6
Wrangler 2.17.0
nodejs v16.20.0
Cloned repo 30 Apr and ensure the updated wrangler.toml 

name = "unifi-cloudflare-ddns"
main = "src/index.js"
compatibility_date = "2023-04-23"
compatibility_flags = [ "nodejs_compat" ]
azureadmin@vm-linux-001:~/unifi-cloudflare-ddns$ 

getting error:

✘ [ERROR] Could not resolve "buffer"

    src/index.js:1:23:
      1 │ import { Buffer } from "buffer";
        ╵                        ~~~~~~~~

  The package "buffer" wasn't found on the file system but is built into node.
  Add "node_compat = true" to your wrangler.toml file to enable Node compatibility.

✘ [ERROR] Build failed with 1 error:

  src/index.js:1:23: ERROR: Could not resolve "buffer"

**Comment by willswire** [comment]
Thanks for raising this issue! Checkout [this branch here ](https://github.com/workerforce/unifi-ddns/tree/fix-buffer-issue) and let me know if it fixes your issue. :)

**Comment by trentrae** [comment]
I was successful with this branch but I also had to install the buffer module.  Thanks you 

npm install buffer
