### ISSUE TITLE
Zone lookup fails

### ISSUE THREAD

**Issue by EmmaRenee** [workerforce/unifi-ddns#35]
I can't seem to get it to recognize my zone. 

`(error) CloudflareApiException Error: Failed to find zone '**snip**.net'`

I see this is just a generic error message from the findZone function. I haven't really dug any deeper to see why it's failing to find a match.  Running the API call from the shell manually using the same API token works fine, however. So, I am ruling out any sort of auth issue.

Before I waste a bunch of time on this, I thought I'd see if you've run into this and what viable solutions you may have found.

**Comment by willswire** [comment]
I haven't run into this before, but it sounds like an auth issue. Have you tried regenerating/rolling the key just to make sure?

**Comment by trentbuffalo** [comment]
Did you happen to find a solution to this? I am having the same issue.

**Comment by JBlaz** [comment]
I am having a similar issue. I have a question about which API key is need for this. During the setup of worker there was an API key created there to created the worker then in the instruction for this repo there was an edit domains key that we created. Which should be the value of the variables in this worker?

**Comment by willswire** [comment]
Yes, the token for your GitHub Actions script is different than the token you'll use to update the zone.
