### ISSUE TITLE
UDM Pro updating record with local IP, not public

### ISSUE THREAD

**Issue by stomko11** [workerforce/unifi-ddns#36]
As the title says - I have set it up according to instructions. However I am getting IP that is configured on the WAN port which is private IP. I was expecting to see the public IP instead. Is this behavior by design or does require some modifications?

**Comment by willswire** [comment]
You should be seeing the public IP. Does your WAN connection on the UniFi portal show a public IP?

**Comment by limpep** [comment]
Having the same issue, its showing an IP, but its not the ISP public IP.

**Comment by victor-marino** [comment]
Hi.

Piggybacking on this to avoid opening a new issue.

In case you guys are not aware, UniFi's DDNS system is completely useless out of the box for people whose UniFi router is behind their ISP router (double NAT).

The reason for this is that UniFi assumes the WAN IP is the public IP, which is of course only true if the UniFi router is directly connected to the internet.

Most decente DDNS services do not do this, and they will instead go out to the actual internet and ask any server what their real public IP is, as seen by them (e.g.: [checkip.dyndns.com](http://checkip.dyndns.com/)).

In fact, many of the DDNS services included in UniFi OS will auto-detect the IP that the request is coming from if you don't provide an IP in your request. Unfortunately, UniFi routers _always_ report the WAN IP in the request... sabotaging the solution to the problem as well.

Do you think it would be possible to have the option of auto-detecting the IP address in your script instead of taking it from the request body? That would be amazing, as now your script would both fix the lack of Cloudflare compatibility _and_ the lack of proper IP autodetection, all at once 😬

**Comment by iceman3k** [comment]
> Hi.
> 
> Piggybacking on this to avoid opening a new issue.
> 
> In case you guys are not aware, UniFi's DDNS system is completely useless out of the box for people whose UniFi router is behind their ISP router (double NAT).
> 
> The reason for this is that UniFi assumes the WAN IP is the public IP, which is of course only true if the UniFi router is directly connected to the internet.
> 
> Most decent DDNS services do not do this, and will instead go out to the actual internet and ask any server what public IP is seen by them (e.g.: [checkip.dyndns.com](http://checkip.dyndns.com/)).
> 
> In fact, many of the DDNS services included in UniFi OS support auto-detecting the IP that the request is coming from - all you have to do is leave the IP field empty in your request. Unfortunately, UniFi routers _always_ report the WAN IP in the request... sabotaging the solution to their own problem 🤦🏻‍♂️
> 
> Do you think it would be possible to have the option of auto-detecting the IP address in your script instead of taking it from the request body? That would be amazing, as now your script would both fix the lack of Cloudflare compatibility _and_ the lack of proper IP autodetection, all at once 😬

While mostly true, Afraid Free DNS works behind double NAT.

**Comment by victor-marino** [comment]
> > Hi.
> > Piggybacking on this to avoid opening a new issue.
> > In case you guys are not aware, UniFi's DDNS system is completely useless out of the box for people whose UniFi router is behind their ISP router (double NAT).
> > The reason for this is that UniFi assumes the WAN IP is the public IP, which is of course only true if the UniFi router is directly connected to the internet.
> > Most decent DDNS services do not do this, and will instead go out to the actual internet and ask any server what public IP is seen by them (e.g.: [checkip.dyndns.com](http://checkip.dyndns.com/)).
> > In fact, many of the DDNS services included in UniFi OS support auto-detecting the IP that the request is coming from - all you have to do is leave the IP field empty in your request. Unfortunately, UniFi routers _always_ report the WAN IP in the request... sabotaging the solution to their own problem 🤦🏻‍♂️
> > Do you think it would be possible to have the option of auto-detecting the IP address in your script instead of taking it from the request body? That would be amazing, as now your script would both fix the lack of Cloudflare compatibility _and_ the lack of proper IP autodetection, all at once 😬
> 
> While mostly true, Afraid Free DNS works behind double NAT.

That's great to know. Maybe Afraid always does auto-detection instead of relying on the IP reported in the request?

Either way, I assume we can't use that to update our own Cloudflare records.

**Comment by iceman3k** [comment]
You can always use a CNAME record to point to the Afraid Free DNS address. You can also modify the worker script to gather the IP that is being reported by Afraid.

**Comment by iceman3k** [comment]
> > > Hi.
> > > Piggybacking on this to avoid opening a new issue.
> > > In case you guys are not aware, UniFi's DDNS system is completely useless out of the box for people whose UniFi router is behind their ISP router (double NAT).
> > > The reason for this is that UniFi assumes the WAN IP is the public IP, which is of course only true if the UniFi router is directly connected to the internet.
> > > Most decent DDNS services do not do this, and will instead go out to the actual internet and ask any server what public IP is seen by them (e.g.: [checkip.dyndns.com](http://checkip.dyndns.com/)).
> > > In fact, many of the DDNS services included in UniFi OS support auto-detecting the IP that the request is coming from - all you have to do is leave the IP field empty in your request. Unfortunately, UniFi routers _always_ report the WAN IP in the request... sabotaging the solution to their own problem 🤦🏻‍♂️
> > > Do you think it would be possible to have the option of auto-detecting the IP address in your script instead of taking it from the request body? That would be amazing, as now your script would both fix the lack of Cloudflare compatibility _and_ the lack of proper IP autodetection, all at once 😬
> > 
> > 
> > While mostly true, Afraid Free DNS works behind double NAT.
> 
> That's great to know. Maybe Afraid always does auto-detection instead of relying on the IP reported in the request?
> 
> Either way, I assume we can't use that to update our own Cloudflare records.

You can always use a CNAME record to point to the Afraid Free DNS address. You can also modify the worker script to gather the IP that is being reported by Afraid.

**Comment by willswire** [comment]
I'm closing this issue as I believe the problem lies in the reporter's network configuration. If the UnifiOS device is being assigned a private IP, that is the IP it will report up to Cloudflare. I suggest applying dynamic DNS configurations at the furthest external network device w/ a public IP
