### ISSUE TITLE
[Resolved] WARNING: cannot connect to unifi-cloudflare-ddns.<worker-subdomain>.workers.dev:443

### ISSUE THREAD

**Issue by jiangtaste** [workerforce/unifi-ddns#39]
Hey Guys,

Here is a tip that can save you hours when using the USG-3P device. 

The problem you may encounter:

```
WARNING: cannot connect to unifi-cloudflare-ddns.<worker-subdomain>.workers.dev:443
WARNING:  file /var/cache/ddclient/ddclient_pppoe0.cache, line 3: Invalid Value for keyword 'ip' = ''
```

Solution to connect USG-3P to unifi-cloudflare-ddns error:

1. Add a custom domain name for unifi-cloudflare-ddns program in Cloudflare, such as `ddns.<your-domain>`
2. Change dyndns server address to the new custom domain name in UniFi Controller
3. This is caused by the outdated ddclient version built-in USG-3P, which cannot validate the ssl of the default multi-level subdomain domain name: `unifi-cloudflare-ddns.<worker-subdomain>.workers.dev`. Adding a custom domain name can fix this issue.

If this is helpful, please upvote to make it more visible. It's recommended the author adds this content to the README.

**Comment by ikoz** [comment]
@jiangtaste I've followed this but still cannot connect. Perhaps ddclient in USG needs an update? to what?
```
WARNING:  cannot connect to ddns.xxx.xxx:443 socket: IO::Socket::SSL: Bad hostname 'ddns.xxx.xxx' IO::Socket::INET configuration failed error:00000000:lib(0):func(0):reason(0)
FAILED:   updating zzz.xxx.xxx: Could not connect to ddns.xxx.xxx.
```

**Comment by jiangtaste** [comment]
> @jiangtaste I've followed this but still cannot connect. Perhaps ddclient in USG needs an update? to what?
> 
> ```
> WARNING:  cannot connect to ddns.xxx.xxx:443 socket: IO::Socket::SSL: Bad hostname 'ddns.xxx.xxx' IO::Socket::INET configuration failed error:00000000:lib(0):func(0):reason(0)
> FAILED:   updating zzz.xxx.xxx: Could not connect to ddns.xxx.xxx.
> ```

No need to upgrade the ddclient in USG. You need to make sure you have configured the correct custom domain for the unifi-cloudflare-ddns worker on Cloudflare.

Here are some debug methods:
1. After you have deployed the unifi-cloudflare-ddns worker on Cloudflare, access this URL in your browser: https://unifi-cloudflare-ddns.<worker-subdomain>.workers.dev/nic/update?myip=<any-ip>&hostname=<your.hostname>
2. You should see "Error: Please provide valid credentials.", it's ok,  this will test if the worker is functioning correctly, 
3. Then, access the URL in your browser: https://<your-custom-domain-for-unifi-cloudflare-ddns-worker>/nic/update?myip=<any-ip>&hostname=<your.hostname>, it should response the same info above.
4. Replace the address in USG with you custom domain.

**Comment by willswire** [comment]
Closing re: @jiangtaste's comment above
