### ISSUE TITLE
Better Instructions For Dummies

### ISSUE THREAD

**Issue by philsward** [workerforce/unifi-ddns#42]
Getting this going with the existing instructions was a bit of a pain. It's not that I needed my hand held... but I kinda needed my hand held. I don't normally need or use nodejs, let alone trying to figure out wrangler, so getting those two working took longer than it needed to.

Here is a suggestion for some slightly more inclusive instructions that might help cut down time for someone like me:

Note #10. I'm not sure if the Read permission is necessary. I've read some places that say it is, but the original instructions don't mention it.

1. Clone this project with git or download to a local folder on your computer.
2. Install NodeJS https://nodejs.org/en
3. If windows, reboot to ensure PATH variables to npm will work properly.
4. Open a command prompt (windows) or terminal (linux/mac)
5. Test to see if npm is working `npm --version` If you get errors, your path variables might be wrong.
6. Install [Wrangler CLI](https://developers.cloudflare.com/workers/wrangler/install-and-update/) on your system using the command `npm -g install wrangler --safe-dev` (-g installs it to a global profile)
8. Test that wrangler works by typing `wrangler version`
9. Log into wrangler by typing `wrangler login` which will open a browser and ask you to login to cloudflare if you aren't already, then allow wrangler as a trusted app.
10. Using the command/terminal prompt, navigate to the directory where you cloned / downloaded and extracted the unifi-ddns project and type the following while in that directory: `wrangler deploy`
11. Once you have created the worker, take note of it's *.workers.dev route. More on routes for Cloudflare Workers [here](https://developers.cloudflare.com/workers/configuration/routing/#routes-with-workersdev).
12. Create an API token so the Worker can update your DNS records. Go to https://dash.cloudflare.com/profile/api-tokens and select "Create token". On the next page, scroll down and click the "Get Started" button next to the "Create Custom Token" label. Select Zone:DNS:Edit for the "Permissions" drop-down, *and add another for Zone:DNS:Read* (is this necessary?), and include your target zone under the "Zone Resources" drop-down. Copy your API Key - you will need it later when configuring your UniFi OS Controller.

Note: By default the worker name is: unifi-cloudflare-ddns
You can change this on the Cloudflare website *Overview -> Workers & Pages* before adding the info into the Unifi console.

**Comment by philsward** [comment]
In addition to the Cloudflare instructions, the following "could" be added to the Unifi instructions to refresh the inadyn cache manually. It doesn't look like a reboot is enough to flush the cache, so it will have to be done manually.

Pulled from: https://www.reddit.com/r/Ubiquiti/comments/gbppr9/udm_force_ddns_update/jqcn35m/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

1. Enable SSH and set a password in the UnifiOS Console Settings (Found in the OS Settings, not the Network Settings)
2. Login to SSH using `root` and the password you created
3. Type `ps aux | grep inadyn`
4. In the output, look for the line `/run/ddns-eth4-inadyn.conf` and note the eth4 number in your environment (this will be different for every environment)
5. Type `inadyn -n -1 --force -f /run/ddns-eth4-inadyn.conf` using the eth(?) number in your environment.

If successful, it will show an update forced for your ddns alias and an updating cache.

**Comment by willswire** [comment]
Thanks for these suggestions @philsward! Could you please submit a PR with your suggested changes? Thanks so much :)

**Comment by philsward** [comment]
@willswire I honestly have no idea how. I'm not at "that level" with this stuff. If I get some time I might play around with it but otherwise it will have to live as a suggestion until someone more capable is willing to take it on.

**Comment by philsward** [comment]
@jabronimus ? "you need to do the same steps on the unifi machine" I never had to run this on the unifi side, only windows. I suppose it "could" be run on the unifi side but won't that get overwritten? The only thing I had to do on the console was refresh the cache.

**Comment by m-d-brown** [comment]
I set this up for the first time a few days ago and needed @philsward's helpful instructions here to make it work.  #53 adds the force update instructions from the second comment here.

**Comment by huwcbjones** [comment]
Wish readme had the improvements from #53 as it would've saved me 20 mins. Have added an addendum for USG devices here: https://github.com/workerforce/unifi-ddns/pull/53/files#r1493766991
> For my USG 3P/USG Pro 4, I needed to look for errors from `ddclient` (`tail -f -n1000 /var/log/messages | grep 'ddclient'`)

**Comment by willswire** [comment]
Closed via #53
