### ISSUE TITLE
Error while creating worker project

### ISSUE THREAD

**Issue by renekcl** [workerforce/unifi-ddns#48]
Hi, 

just found this nice solution and tried to deploy it for my domain. I choose the "click to deploy" method but ended up with an error while the project should be created. Tried it several times, deleted the github fork, recreated the api token.

I created a token from template "Edit Cloudflare Workers". 

Any ideas? The cloudflare worker dashboard is still empty

![image](https://github.com/workerforce/unifi-ddns/assets/87851527/a1f74e11-f906-47f8-8de4-64188c25b277)

**Comment by renekcl** [comment]
I checked the actions in Github and no action was created. I have now added the action manually in Github (action -> new workflow) and inserted the code of the deploy.yml. Now I see two workflows in Github. 

![image](https://github.com/workerforce/unifi-ddns/assets/87851527/59e3905c-9941-4c2e-b3ef-7f300c606924)

Under Cloudflare Workers & Pages "unifi-cloudflare-ddns" was created. Does this correspond to what the Click to Deploy process should do?

**Comment by kmax9981** [comment]
I too get the same "Project had an error" when deploying, The API did not have a worker option by itself, there were several worker options for the API so I added them all just to test.  I followed all the instructions listed and do not know where to go from here.

**Comment by BovBrew** [comment]
I got stuck with the same issue but I went to "Deploy" under workers and edited. I didn't actually do anything I just deleted lines and added it back. When you commit the changes it auto deploys and it worked.

**Comment by MatthewA1** [comment]
I wonder if this is somehow related to the repository name not being the same as the worker name. I assume the "Deploy with Workers" tool does some initial manual deployment since the action would not ever run immediately after being activated once forked.
The message says:
>Congratulations, **unifi-ddns** is now deploying!

However, the actual package name is `unifi-cloudflare-ddns`:
https://github.com/workerforce/unifi-ddns/blob/f9f695ab9599c2271b405def96360196d5533071/wrangler.toml#L1

**Comment by JBlaz** [comment]
I am also getting this error. The JSON response that comes in when error appears is:
```
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest"
}
```
Seems like the wrong name could be the issue.

**Comment by JBlaz** [comment]
> I checked the actions in Github and no action was created. I have now added the action manually in Github (action -> new workflow) and inserted the code of the deploy.yml. Now I see two workflows in Github.
> 
> ![image](https://private-user-images.githubusercontent.com/87851527/297991787-59e3905c-9941-4c2e-b3ef-7f300c606924.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NzczNTUsIm5iZiI6MTcwNjk3NzA1NSwicGF0aCI6Ii84Nzg1MTUyNy8yOTc5OTE3ODctNTllMzkwNWMtOTk0MS00YzJlLWIzZWYtN2YzMDBjNjA2OTI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDE2MTczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0NzVhYTczZDY0NTc1NjI3MTZmNmZiMDI1Y2I4MWQyNDQ2MmRkMWY5NTdkYTQ4N2FiNGFhNzY1NDJmMzQzNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LBo1kvRONedrQ8TWV5Ym84bgNHV_4j8fB8DDSlKUD6E)
> 
> Under Cloudflare Workers & Pages "unifi-cloudflare-ddns" was created. Does this correspond to what the Click to Deploy process should do?

I did this same thing. Deleted the one I created and it was mostly working from there. I created one with no content just a worker that did nothing and it worked fine after that. Something must have changed with GitHub and how workers are enabled.

**Comment by norimicry** [comment]
Also unable to use the Click to Deploy option

**Comment by toonamowasstolen** [comment]
Was not able to get the click to deploy to work either. There was no information on the error either. when i went to actions it shows no runs yet.

so i tried the wrangler option and deploy gave an errror the entry-point file was not found.

so i tried wrangler dev and that created some files and when i opened in a browser it gave an error to use https even though it was using https. after that deploy worked but every time i visit the worker through cloudflare it use shows not found.

i'm probably doing something wrong but have no idea where to start or look.

**Comment by Rubeast** [comment]
I also solved it by editing the deploy.yml (just add some empty lines and delete them) on my github page and re-executing the "Deploy the Worker" step.

Thx @BovBrew !

**Comment by MatthewA1** [comment]
It seems like the solution is to just add `workflow_dispatch` to the workflow so that you can manually run the deployment once. Having users manually edit a file just to force a workflow to run seems like a recipe for disaster if they ever want to contribute back to this repo from their forks.
@willswire It's a one line change, but I opened a PR since this issue has already been closed

**Comment by Rubeast** [comment]
Yeah. I don't understand why it is being marked as completed. What we had to do is more a workaround. 
@willswire, are you expecting that every user needs to edit the deploy.yml file?

**Comment by willswire** [comment]
The PR by @MatthewA1 should fix this. Users shouldn't need to edit the `deploy.yml` file, but they will need to set their own API key and Account ID in their GitHub project fork's settings (under _Actions secrets and variables_)

**Comment by MatthewA1** [comment]
@Rubeast The PR I made was merged, so you should be able to just run the workflow manually from the Actions page now. You'll see a notice and button that look like this:
![image](https://github.com/workerforce/unifi-ddns/assets/22651099/2b058a36-f3a9-449c-9d92-9f69932605da)
