### ISSUE TITLE
Multiple domains updating via UDM Pro

### ISSUE THREAD

**Issue by chrismast** [workerforce/unifi-ddns#55]
Hi All,

First of all thanks for this great work!
I got it working with one of my domains via the UDM Pro after a bit of trouble deploying the walker (one of the issues here solved it though).
I got though 2 domains to update (i.e. xjh.net and xhh.com) but the UDM Pro somehow seems to only allow one entry for dyndns.
Is there any workaround that I could deploy?

Cheers

**Comment by willswire** [comment]
at this point in time, I am not aware of UnifiOS supporting multiple domains. One way to approach this problem is to have one of your domains point to the other? `something.xjh.net -> something.xhh.com`
